export const EVENT_EMITTER_PRESET_SELECTED = 'EVENT_EMITTER_PRESET_SELECTED';
export const EVENT_EMITTER_PRESET_REMOVED = 'EVENT_EMITTER_PRESET_REMOVED';
export const EVENT_EMITTER_INFINITE_CHANGED = 'EVENT_EMITTER_INFINITE_CHANGED';
export const EVENT_EMITTER_CORE_CHANGED = 'EVENT_EMITTER_CORE_CHANGED';
export const EVENT_EMITTER_CORE_PARAMS_CHANGED = 'EVENT_EMITTER_CORE_PARAMS_CHANGED';
export const EVENT_EMITTER_ROTATION_CHANGED = 'EVENT_EMITTER_ROTATION_CHANGED';
export const EVENT_EMITTER_AUTO_ROTATION_CHANGED = 'EVENT_EMITTER_AUTO_ROTATION_CHANGED';
export const EVENT_EMITTER_CHILDS_CHANGED = 'EVENT_EMITTER_CHILDS_CHANGED';

export const EVENT_SEQUENCE_PRESET_SELECTED = 'EVENT_SEQUENCE_PRESET_SELECTED';
export const EVENT_SEQUENCE_PRESET_REMOVED = 'EVENT_SEQUENCE_PRESET_REMOVED';

export const EVENT_RESET = 'EVENT_RESET';
